AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Stack - Creates Role, Group, and Two Users with EC2 Policy'

Mappings:
  Config:
    Names:
      PolicyName: EC2FullAccessPolicy
      RoleName: AWS-CloudChapsRole
      GroupName: AWS-CloudChapsGroup
      User1Name: AWS-CloudChapsUser
      User2Name: AWS-CloudChapsUserTwo

Resources:
  EC2Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !FindInMap [Config, Names, PolicyName]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 'ec2:*'
            Effect: Allow
            Resource: '*'
          - Effect: Allow
            Action: 'elasticloadbalancing:*'
            Resource: '*'
          - Effect: Allow
            Action: 'cloudwatch:*'
            Resource: '*'
          - Effect: Allow
            Action: 'autoscaling:*'
            Resource: '*'
          - Effect: Allow
            Action: 'iam:CreateServiceLinkedRole'
            Resource: '*'
            Condition:
              StringEquals:
                iam:AWSServiceName:
                  - autoscaling.amazonaws.com
                  - ec2scheduled.amazonaws.com
                  - elasticloadbalancing.amazonaws.com
                  - spot.amazonaws.com
                  - spotfleet.amazonaws.com
                  - transitgateway.amazonaws.com

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !FindInMap [Config, Names, RoleName]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref EC2Policy

  IAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !FindInMap [Config, Names, GroupName]
      ManagedPolicyArns:
        - !Ref EC2Policy

  IAMUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: !FindInMap [Config, Names, User1Name]
      Groups:
        - !Ref IAMGroup
      ManagedPolicyArns:
        - !Ref EC2Policy

  IAMUser2:
    Type: AWS::IAM::User
    Properties:
      UserName: !FindInMap [Config, Names, User2Name]
      ManagedPolicyArns:
        - !Ref EC2Policy

Outputs:
  RoleName:
    Value: !Ref IAMRole
    Description: IAM Role Name
  GroupName:
    Value: !Ref IAMGroup
    Description: IAM Group Name
  User1Name:
    Value: !Ref IAMUser1
    Description: First IAM User Name
  User2Name:
    Value: !Ref IAMUser2
    Description: Second IAM User Name
